const UNCLASSIFIED = "__unclassified";

const TREE = {
  meta: {
    id: "1",
    title: "DOLCE Decision Diagram v2",
    description: "The D3 decision tree to help choose a DOLCE category.",
  },

  nodes: {
    "1": { kind: "question", concept: "Particular", text: "Is [] something that is happening or occurring?",
      options: [ { label: "Yes", next: "1.1" }, { label: "No", next: "1#1" } ] },
    "1#1": { kind: "question", concept: "Particular", text: "Is [] wholly present at any time of its existence?",
      options: [ { label: "Yes", next: "1.2" }, { label: "No", next: "1#2" } ] },
    "1#2": { kind: "question", concept: "Particular", text: "Does [] exist neither in space nor in time, or does so because some other items that are not among its parts occupy that region?",
      options: [ { label: "Yes", next: "1.3" }, { label: "No", next: "1#3" } ] },
    "1#3": { kind: "question", concept: "Particular", text: "Is [] something that can be perceived or measured (like colour, size, smell, etc.)?",
      options: [ { label: "Yes", next: "1.4" }, { label: "No", next: "__unclassified" } ] },

    "1.1": { kind: "question", concept: "Perdurant", text: "Are you able to be present or participate in []?",
      options: [ { label: "Yes", next: "1.1.1" }, { label: "No", next: "1.1.2" } ] },
    "1.1.1": { kind: "question", concept: "Event", text: "Is [] atomic, i.e., has no subdivisions of it, and does it have a definite end point?",
      options: [ { label: "Yes", next: "1.1.1.1" }, { label: "No", next: "1.1.1.2" } ] },
    "1.1.1.1": { kind: "result", concept: "Event", category: "Achievement" },
    "1.1.1.2": { kind: "result", concept: "Event", category: "Accomplishment" },
    "1.1.2": { kind: "question", concept: "Stative", text: "Are you able to undergo, experience, or be subjected to []? Or: is each time slice of [] the same kind of thing?",
      options: [ { label: "Yes", next: "1.1.2.1" }, { label: "No", next: "1.1.2.2" } ] },
    "1.1.2.1": { kind: "result", concept: "Stative", category: "State" },
    "1.1.2.2": { kind: "result", concept: "Stative", category: "Process" },

    "1.2": { kind: "question", concept: "Endurant", text: "Is [] a collection of things, regardless of their spatial or other differences?",
      options: [ { label: "Yes", next: "1.2.1" }, { label: "No", next: "1.2.2" } ] },
    "1.2.1": { kind: "result", concept: "Endurant", category: "ArbitrarySum" },
    "1.2.2": { kind: "question", concept: "NonPhysicalOrDependent", text: "Does [] need some other object to exist in, or is [] a role played by some object, or does [] not take up space? (e.g., a student)",
      options: [ { label: "Yes", next: "1.2.2.2" }, { label: "No", next: "1.2.2.1" } ] },
    "1.2.2.1": { kind: "question", concept: "PhysicalEndurant", text: "Does [] exist insofar as its host exists (like holes, bumps, boundaries, or spots of colour)?",
      options: [ { label: "Yes", next: "1.2.2.1.1" }, { label: "No", next: "1.2.2.1.2" } ] },
    "1.2.2.1.1": { kind: "result", concept: "PhysicalEndurant", category: "Feature" },
    "1.2.2.1.2": { kind: "question", concept: "PhysicalEndurant", text: "Is [] something that cannot be counted, or only in specific quantities?",
      options: [ { label: "Yes", next: "1.2.2.1.2.1" }, { label: "No", next: "1.2.2.1.2.2" } ] },
    "1.2.2.1.2.1": { kind: "result", concept: "PhysicalEndurant", category: "AmountOfMatter" },
    "1.2.2.1.2.2": { kind: "question", concept: "PhysicalObject", text: "Does [] have beliefs, desires, and intentions?" ,
      options: [ { label: "Yes", next: "1.2.2.1.2.2.1" }, { label: "No", next: "1.2.2.1.2.2.2" } ] },
    "1.2.2.1.2.2.1": { kind: "result", concept: "PhysicalObject", category: "AgentivePhysicalObject" },
    "1.2.2.1.2.2.2": { kind: "result", concept: "PhysicalObject", category: "NonAgentivePhysicalObject" },    
    "1.2.2.2": { kind: "question", concept: "NonPhysicalEndurant", text: "Is [] dependent on a community of (i.e., >1) agents or is it embedded in some social setting?",
      options: [ { label: "Yes", next: "1.2.2.2.1" }, { label: "No", next: "1.2.2.2.2" } ] },
    "1.2.2.2.1": { kind: "result", concept: "NonPhysicalEndurant", category: "SocialObject" },
    "1.2.2.2.2": { kind: "result", concept: "NonPhysicalEndurant", category: "MentalObject" },

    "1.3": { kind: "question", concept: "Abstract", text: "Is [] a collection of well defined objects?",
      options: [ { label: "Yes", next: "1.3.1" }, { label: "No", next: "1.3#1" } ] },
    "1.3#1": { kind: "question", concept: "Abstract", text: "Is [] a piece of information about something that exists or has happened?",
      options: [ { label: "Yes", next: "1.3.2" }, { label: "No", next: "1.3#2" } ] },
    "1.3#2": { kind: "question", concept: "Abstract", text: "Is [] a location of or occupied by some object?",
      options: [ { label: "Yes", next: "1.3.3" }, { label: "No", next: "__unclassified" } ] },
    "1.3.1": { kind: "result", concept: "Abstract", category: "Set" },
    "1.3.2": { kind: "result", concept: "Abstract", category: "Fact" },
    "1.3.3": { kind: "question", concept: "Region", text: "Can only physical qualities (attributes) of physical objects be located in this region?",
     options: [ { label: "Yes", next: "1.3.3.1" }, { label: "No", next: "1.3.3#1" } ] },
    "1.3.3.1": { kind: "question", concept: "PhysicalRegion", text: "Is [] an ordinary space, be it geographical, cosmological, topographic?",    
     options: [ { label: "Yes", next: "1.3.3.1.1" }, { label: "No", next: "__unclassified" } ] },    
    "1.3.3.1.1": { kind: "result", concept: "PhysicalRegion", category: "SpaceRegion" },       
    "1.3.3#1": { kind: "question", concept: "Region", text: "Can only temporal qualities (attributes) of events, states, or processes be located in this region?",  
     options: [ { label: "Yes", next: "1.3.3.2" }, { label: "No", next: "1.3.3.3" } ] },     
    "1.3.3.2": { kind: "question", concept: "TemporalRegion", text: "Is [] measured in, e.g., seconds or days?" ,     
    options: [ { label: "Yes", next: "1.3.3.2.1" }, { label: "No", next: "__unclassified" } ] },    
    "1.3.3.2.1": { kind: "result", concept: "TemporalRegion", category: "TimeInterval" },     
    "1.3.3.3": { kind: "result", concept: "Region", category: "AbstractRegion" },          

    "1.4": { kind: "question", concept: "Quality", text: "Is [] an attribute of a (physical) object?",
      options: [ { label: "Yes", next: "1.4.1" }, { label: "No", next: "1.4.2" } ] },
    "1.4.1": { kind: "question", concept: "PhysicalQuality", text: "Is [] located in (or: whose value is given within) ordinary spaces, such as geographical coordinates, cosmological positions, or anatomical axes?" ,
      options: [ { label: "Yes", next: "1.4.1.1" }, { label: "No", next: "__unclassified" } ] },
     "1.4.1.1": { kind: "result", concept: "PhysicalQuality", category: "SpatialLocation" },   
    "1.4.2": { kind: "question", concept: "Quality", text: "Is [] an attribute of something that is happening or occurring?",
      options: [ { label: "Yes", next: "1.4.2.1" }, { label: "No", next: "1.4.2.2" } ] },
    "1.4.2.1": { kind: "question", concept: "TemporalQuality", text: "Is [] located in (or: whose value is given within) ordinary times, such as a day on the Gregorian calendar?" ,
       options: [ { label: "Yes", next: "1.4.2.1.1" }, { label: "No", next: "__unclassified" } ] },
     "1.4.2.1.1": { kind: "result", concept: "TemporalQuality", category: "TemporalLocation" },      
    "1.4.2.2": { kind: "result", concept: "Quality", category: "AbstractQuality" },
  },
};

for (const [id, node] of Object.entries(TREE.nodes)) node.id = id;

export { TREE, UNCLASSIFIED };
